### ISSUE TITLE
Create database for sshotel

### ISSUE THREAD

**Issue by mjks4545** [mjks4545/sshotel#1]
Check different database online and create something similar accourding to the needs of sshotel...

**Comment by Rahman4545** [comment]
Proposal of Final Project.

Title of Project: Academy Management system.

Advisor name: Mr.Said-ul-abrar

Supervisor Name: Mr.Sadiq Shah

Submitted By

Group Member: Rahman Ali    (167)

```
                      Wasim Ullah   (154)

                      Imran              (128)
```

​​​Bs(CS) 8th Section C

Submitted to

Sir Sadiq Shah

Institute of Business and Management Sciences

The University of Agriculture Peshawar, Department.

Introduction:

This project consists of a web development to present project proposal for
the Final Project of BS (cs).We try to develop something new in development
side so we create the academy of management for academy. There are some
more new projects or new ideas to present in this proposal but we learn the
web development basics in start-up our career.

Features and functionality of this system:

Academy management system is a web based application, which is proposed to
develop to the Academy accounts system of students, teachers and their
courses. This management system focuses on the academy courses and
teachers’ salaries percentage on the basis of courses.
This system requires the use of simple device like a personal computer.

Possible areas of application:

This project can be used for only academy management which has announced
many courses for their students.

Objectives of the project:

Main objectives of this system include:
• Academy students register.
• Student’s fees system and their fee slips.
• Teacher Salaries system on the basis of courses.
• Reports generates automatically.

Languages to be used:
• Html
• Css
• JavaScript
• PHP
• Adobe Dream viewer
• Mysql (Database)
